update all shell to set BASE_DIR and load include

diff --git a/bin/setinit b/bin/setinit
--- a/bin/setinit
+++ b/bin/setinit
@@ -8,11 +8,18 @@
 # Return Code: 0|1
 # 
 
-[ -z "${BASE_DIR}" ] && {
-        path=$(cd $(dirname $0) && pwd)
-        BASE_DIR=${path%/*}
-        source ${BASE_DIR}/bin/include 2>&-
-}
+BASE_DIR="/usr/local/eminfo"
+if [ -f ${BASE_DIR}/bin/include -a -s ${BASE_DIR}/bin/include ]; then
+        source ${BASE_DIR}/bin/include 2>&1
+        rc=$?
+        [ "$rc" != "0" ] && {
+                echo "load include file failed with status $rc"
+                exit 1
+        }
+else
+        echo "${BASE_DIR}/bin/include not exist or empty. exit" 
+        exit 1
+fi
 
 
 [ -f "/usr/bin/cksum" -a -x "/usr/bin/cksum" ] || {
