all inners output like plugins' format

diff --git a/plugin/.inner/eminfo_clear_overdue b/plugin/.inner/eminfo_clear_overdue
--- a/plugin/.inner/eminfo_clear_overdue
+++ b/plugin/.inner/eminfo_clear_overdue
@@ -4,18 +4,35 @@
 # Inner Plugin:  periodic clear tmpfiles logfiles snapfiles.
 #
 
-if [ -z "${BASE_DIR}" ]; then
-	path=$(cd $(dirname $0) && pwd)  
-	BASE_DIR=${path%/*}
-	BASE_DIR=${BASE_DIR%/*}
-	source ${BASE_DIR}/bin/include 2>&-
+BASE_DIR="/usr/local/eminfo"
+if [ -f ${BASE_DIR}/bin/include -a -s ${BASE_DIR}/bin/include ]; then
+        source ${BASE_DIR}/bin/include 2>&1
+        rc=$?
+        [ "$rc" != "0" ] && {
+                echo "load include file failed with status $rc"
+                exit 1
+        }   
+else
+        echo "${BASE_DIR}/bin/include not exist or empty. exit" 
+        exit 1
 fi
 
+# Return Codes
+STATE_OK=0
+STATE_WARNING=1
+STATE_CRITICAL=2
+STATE_UNKNOWN=3
+STATE_NOOP=4
 
+# Set Default
+EXIT_STATUS=0
+LEVEL=          ### { ok | warn | crit | unknown }
+TYPE=           ### { str| file }
+CONTENT=        ### { strings | /path/to/result.file }
 
 # Read plugin config value here
-tmpfile_reserve_time=$( read_eminfo_config eminfo_clear_overdue tmpfile_reserve_time)
-logfile_reserve_time=$( read_eminfo_config eminfo_clear_overdue logfile_reserve_time)
+tmpfile_reserve_time=$( read_eminfo_config eminfo_clear_overdue tmpfile_reserve_time )
+logfile_reserve_time=$( read_eminfo_config eminfo_clear_overdue logfile_reserve_time )
 snapfile_reserve_time=$( read_eminfo_config eminfo_clear_overdue snapfile_reserve_time )
 snapdir_maxsize=$( read_eminfo_config eminfo_clear_overdue snapdir_maxsize )
 
@@ -32,23 +49,34 @@ check() {
   local total_num=0  t_num=0  l_num=0  s_num=0
 
   # First check if the top directories which to be searched is invalid or not.
-  # You must take care here becase it releated to deletion operations.
+  # You must take care here because it releated to deletion operations.
   # If one of the following three variables is invalid, exit.
   [ "$( sub_str "${TMP_DIR}" "eminfo/tmp" )" == "no" ] && {
-	result="Critical Error: TMP_DIR [${TMP_DIR}] is invalid"
-	echo "${result}"
-	return 1
+	EXIT_STATUS=${STATE_CRIT};
+	LEVEL="unknown";
+	TYPE="str";
+	CONTENT="Critical Error: TMP_DIR [${TMP_DIR}] is invalid";
+	return
   }
   [ "$( sub_str "${BACK_DIR}" "eminfo/log/backup" )" == "no" ] && {
-	result="Critical Error: BACK_DIR [${BACK_DIR}] is invalid"
-	echo "${result}"
-	return 1
+        EXIT_STATUS=${STATE_CRIT};
+        LEVEL="unknown";
+        TYPE="str";
+	CONTENT="Critical Error: BACK_DIR [${BACK_DIR}] is invalid"
+	return
   }
   [ "$( sub_str "${SNAPSHOT_DIR}" "eminfo/log/snapshot" )" == "no" ] && {
-	result="Critical Error: SNAPSHOT_DIR [${SNAPSHOT_DIR}] is invalid"
-	echo "${result}"
-	return 1
+        EXIT_STATUS=${STATE_CRIT};
+        LEVEL="unknown";
+        TYPE="str";
+        CONTENT="Critical Error: SNAPSHOT_DIR [${SNAPSHOT_DIR}] is invalid"
+	return
   }
+
+  # Search files by /usr/bin/find with option -follow  (this maybe dangerous)
+  # This may be very dangerous if somebody created a symbolic link like this:
+  # ln -sv /etc/  eminfo/log/snapshot/
+  # Hope nobody would be stupid like that
 
   # 1. search tmpfiles
 
@@ -63,43 +91,43 @@ check() {
 
   # search tmpfiles in tmpdirs.
   [ -z "${tmpfile_dirlist//[ ]/}" ] && {
-	result="${result} tmpfile: No temperary directories be searched;" 
+	result="${result} tmpfile: No temperary directories be searched ###" 
   } || {
-	tmpfiles=$( find ${tmpfile_dirlist} -follow -type f -ctime +${tmpfile_reserve_time} -print 2>&- )
+	tmpfiles=$( /usr/bin/find ${tmpfile_dirlist} -follow -type f -ctime +${tmpfile_reserve_time} -print 2>&- )
 	[ -z "${tmpfiles}" ] && {
 		t_num=0
 	} || {
 		t_num=$(echo -e "${tmpfiles}" | wc -l)
 	}
 	dellist="${dellist} ${tmpfiles} \n"   ### \n here is important
-  	result="${result} tmpfile: ${t_num} files;"
+  	result="${result} tmpfile: ${t_num} files ###"
   }
 
   # 2. search logfiles
-  logfiles=$( find ${BACK_DIR} -follow -type f -ctime +${logfile_reserve_time} -print 2>&- )
+  logfiles=$( /usr/bin/find ${BACK_DIR} -follow -type f -ctime +${logfile_reserve_time} -print 2>&- )
   [ -z "${logfiles}" ] && {
 	l_num=0
   } || {
   	l_num=$(echo -e "${logfiles}" | wc -l)
   }
   dellist="${dellist} ${logfiles} \n"   ### \n here is important
-  result="${result} logfile: ${l_num} files;"
+  result="${result} logfile: ${l_num} files ###"
 
   # 3. search snapfiles
-  snapfiles=$( find ${SNAPSHOT_DIR} -follow -type f -ctime +${snapfile_reserve_time} -print 2>&- )
+  snapfiles=$( /usr/bin/find ${SNAPSHOT_DIR} -follow -type f -ctime +${snapfile_reserve_time} -print 2>&- )
   [ -z "${snapfiles}" ] && {
 	s_num=0
   } || {
   	s_num=$(echo -e "${snapfiles}" | wc -l)
   }
   dellist="${dellist} ${snapfiles} \n"   ### \n here is important
-  result="${result} snapfiles: ${s_num} files;"
+  result="${result} snapfiles: ${s_num} files ###"
 
   total_num=$(( ${t_num} + ${l_num} + ${s_num} ))
   [ "${total_num}" == "0" ] && {
-	result="No file to be cleaned up;" 
+	result="No file to be cleaned up ###" 
   } || {
-	result="${result} total: ${total_num} files to be cleaned up: $( echo -e "${dellist}" | tr '\n' ' ' ); "
+	result="${result} total: ${total_num} files to be cleaned up: $(echo -e "${dellist}" | tr '\n' ' ') ###"
   }
 
   # 4. delete files
@@ -111,30 +139,37 @@ check() {
 
   # 5. check snapdir_maxsize
   # remove oldest directory if {SNAPSHOT_DIR} maxsize exceed 
-  snap_dirsize=$( du -sm "${SNAPSHOT_DIR}" 2>&- | awk '{print $1}' )
+  snap_dirsize=$( /usr/bin/du -sm "${SNAPSHOT_DIR}" 2>&- | awk '{print $1}' )
   if [ -z "${snap_dirsize}" -o ! -z "${snap_dirsize//[0-9]}" ]; then
-	result="${result} snap directory size invalid [${snap_dirsize}]."
+	result="${result} snap directory size invalid [${snap_dirsize}] ###"
   else
   	if [ $snap_dirsize -gt ${snapdir_maxsize} ]; then
-		result="${result} snap directory size [${snap_dirsize}M] >= [${snapdir_maxsize}M], cleaning up"
-		oldestdir=$( find "${SNAPSHOT_DIR}" -mindepth 1 -maxdepth 1 | sort -n | head -n1)
+		result="${result} snap directory size [${snap_dirsize}M] >= [${snapdir_maxsize}M], cleaning up ###"
+		oldestdir=$( /usr/bin/find "${SNAPSHOT_DIR}" -mindepth 1 -maxdepth 1 | sort -n | head -n1)
 		if [ "$( sub_str "${oldestdir}" "eminfo/log/snapshot/" )" == "yes" ]; then
-			result="${result}; oldest dir: [${oldestdir}] will be removed"
+			result="${result} oldest dir: [${oldestdir}] will be removed ###"
 			rmerr=$( /bin/rm -rf "${oldestdir}" 2>&1 1>/dev/null )
 			if [ "$?" == "0" ]; then
-				result="${result}; remove [${oldestdir}] success."
+				result="${result} remove [${oldestdir}] success ###"
 			else
-				result="${result}; remove [${oldestdir}] failed: [${rmerr}]."
+				result="${result} remove [${oldestdir}] failed: [${rmerr}] ###"
 			fi
 		else
-       			result="${result}; oldest dir: [${oldestdir}] is invalid, nothing to do."
+       			result="${result} oldest dir: [${oldestdir}] is invalid, nothing to do ###"
 		fi
 	else
-		result="${result} snap directory size [${snap_dirsize}M], nothing to do."
+		result="${result} snap directory size [${snap_dirsize}M], nothing to do ###"
   	fi
   fi
 
-  echo "${result}"
+  EXIT_STATUS="${STATE_OK}"
+  LEVEL="ok"
+  TYPE="str"
+  CONTENT="Clear_Overdue Files Finished | No Alert | ${result}"
 }
 
 check
+
+# output result and return exit status here.
+echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
+exit ${EXIT_STATUS}  
diff --git a/plugin/.inner/eminfo_iam_alive b/plugin/.inner/eminfo_iam_alive
--- a/plugin/.inner/eminfo_iam_alive
+++ b/plugin/.inner/eminfo_iam_alive
@@ -4,14 +4,31 @@
 # Inner Plugin:  periodic post heartbeat.
 #
 
-if [ -z "${BASE_DIR}" ]; then
-        path=$(cd $(dirname $0) && pwd)  
-        BASE_DIR=${path%/*}
-        BASE_DIR=${BASE_DIR%/*}
-        source ${BASE_DIR}/bin/include 2>&-
+BASE_DIR="/usr/local/eminfo"
+if [ -f ${BASE_DIR}/bin/include -a -s ${BASE_DIR}/bin/include ]; then
+        source ${BASE_DIR}/bin/include 2>&1
+        rc=$?
+        [ "$rc" != "0" ] && {
+                echo "load include file failed with status $rc"
+                exit 1
+        }   
+else
+        echo "${BASE_DIR}/bin/include not exist or empty. exit" 
+        exit 1
 fi
 
+# Return Codes
+STATE_OK=0
+STATE_WARNING=1
+STATE_CRITICAL=2
+STATE_UNKNOWN=3
+STATE_NOOP=4
 
+# Set Default
+EXIT_STATUS=0
+LEVEL=          ### { ok | warn | crit | unknown }
+TYPE=           ### { str| file }
+CONTENT=        ### { strings | /path/to/result.file }
 
 # Read plugin config value here
 post_server=$(read_eminfo_config postlog post_server)
@@ -39,21 +56,41 @@ post_server_port=$(read_eminfo_config postlog post_server_port)
 # check function here
 check() {
   local result=
-  [ -z "${post_server//[ ]}" -o -z "${queue_name//[ ]}" -o -z "${auth_pass//[ ]}" ] && {
-	result="Critical Error: configurations not complete, [post_server,queue_name,auth_pass can't be empty]. EXIT"
+  [ -z "${post_server}" -o -z "${queue_name}" -o -z "${auth_pass}" ] && {
+        EXIT_STATUS=${STATE_CRIT};
+        LEVEL="unknown";
+        TYPE="str";
+	CONTENT="Critical Error | configurations not complete | post_server,queue_name,auth_pass can't be empty."
         return
   }
-  local eminfo_id=$(get_eminfo_id) timestamp=$(date +%s)
+  local eminfo_id=$(get_eminfo_id) 
+  [ -z "${eminfo_id}" ] && {
+	EXIT_STATUS=${STATE_CRIT};
+	LEVEL="unknown";
+	TYPE="str";
+	CONTENT="Critical Error | eminfo id empty | maybe you need to exec setint"
+	return
+  }
+  local timestamp=$(date +%s)
   local heartbeat="eminfo_id=${eminfo_id}  timestamp=${timestamp}  heartbeat=iamalive"
   local postdata=$(echo -n "${heartbeat}" | /usr/bin/od -t x1 -A n -w1000 | tr " " "%" | tr -d '\r\n')
   # curl -s: silient
   result=$( /usr/bin/curl -k -s --connect-timeout ${post_time_out} -d "${postdata}" "https://${post_server}:${post_server_port}/?charset=${charset}&name=${queue_name}&opt=put&auth=${auth_pass}"  2>&1 )
   if [ "$?" == "0" ]; then
-	result="SUCCESS: post heartbeat=[${heartbeat}] result=[${result}]"
+	EXIT_STATUS="${STATE_OK}"
+	LEVEL="ok"
+	TYPE="str"
+	CONTENT="Heartbeat Success | post heartbeat success | post heartbeat=[${heartbeat}] ### result=[${result}] ###"
   else
-	result="FAIL: post heartbeat=[${heartbeat}] result=[${result}]"
+	EXIT_STATUS="${STATE_WARNING}"
+	LEVEL="warn"
+	TYPE="str"
+	CONTENT="Heartbeat FAIL | post heartbeat failed | post heartbeat=[${heartbeat}] ### result=[${result}] ### maybe timeout on connect ${post_server}:${post_server_port} ###"
   fi
-  echo -e "${result}"
 }
 
 check
+
+# output result and return exit status here.
+echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
+exit ${EXIT_STATUS}  
diff --git a/plugin/.inner/eminfo_log_rotate b/plugin/.inner/eminfo_log_rotate
--- a/plugin/.inner/eminfo_log_rotate
+++ b/plugin/.inner/eminfo_log_rotate
@@ -4,14 +4,31 @@
 # Inner Plugin:  periodic rollback logfiles.
 #
 
-if [ -z "${BASE_DIR}" ]; then
-	path=$(cd $(dirname $0) && pwd)  
-	BASE_DIR=${path%/*}
-	BASE_DIR=${BASE_DIR%/*}
-	source ${BASE_DIR}/bin/include 2>&-
+BASE_DIR="/usr/local/eminfo"
+if [ -f ${BASE_DIR}/bin/include -a -s ${BASE_DIR}/bin/include ]; then
+        source ${BASE_DIR}/bin/include 2>&1
+        rc=$?
+        [ "$rc" != "0" ] && {
+                echo "load include file failed with status $rc"
+                exit 1
+        }   
+else
+        echo "${BASE_DIR}/bin/include not exist or empty. exit" 
+        exit 1
 fi
 
+# Return Codes
+STATE_OK=0
+STATE_WARNING=1
+STATE_CRITICAL=2
+STATE_UNKNOWN=3
+STATE_NOOP=4
 
+# Set Default
+EXIT_STATUS=0
+LEVEL=          ### { ok | warn | crit | unknown }
+TYPE=           ### { str| file }
+CONTENT=        ### { strings | /path/to/result.file }
 
 # Read plugin config value here
 force_size_uplimit=$( read_eminfo_config eminfo_log_rotate force_size_uplimit )
@@ -21,7 +38,7 @@ force_size_uplimit=$( read_eminfo_config eminfo_log_rotate force_size_uplimit )
 
 # check function here
 check() {
-  local result=
+  local result= rollnum=0
   array_logfiles=( 
 		${EMINFO_LOG} 
 		${INNER_LOG} 
@@ -38,11 +55,11 @@ check() {
 
   for file in  ${array_logfiles[@]}
   do
-	[ -f "${file}" ] && {
+	if [ -f "${file}" ]; then
 
 		## 1. check filesize
-		local size=$( du -sm "${file}" 2>&- | awk '{print $1}' )
-		[ -z "${size}"  -o ! -z "${size//[0-9]}" ] || {
+		local size=$( /usr/bin/du -sm "${file}" 2>&- | awk '{print $1}' )
+		if [ -z "${size}"  -o ! -z "${size//[0-9]}" ]; then
 			[ "$( echo "${size} >= ${force_size_uplimit}" | bc )" == "1" ] &&  {
 				local basefile="${BACK_DIR}/${file##*/}.$(date +%F).${size}M"
 				local dstfile="${basefile}"
@@ -54,10 +71,11 @@ check() {
 				done
 
 		    		mv  "${file}" "${dstfile}" 2>&-
-		    		result="${result} [${file}] filesize:[${size}M >= ${force_size_uplimit}M]: roll back [${file}] => [${dstfile}];"
+				((rollnum++))
+		    		result="${result} [${file}] filesize:[${size}M >= ${force_size_uplimit}M] ### rollback:[${dstfile}] ### ### "
 		    		continue
 			}
-		}
+		fi
 
 		## 2. check current time : the begining of newday or not
 		local day_start=$(date -d "" +%s)     ### the begining of today
@@ -75,7 +93,8 @@ check() {
 			done	
 			
 			mv "${file}" "${dstfile}" 2>&-
-			result="${result} [${file}] newday begin:[$(date +%F_%T)]: roll back [${file}] => [${dstfile}];"
+			((rollnum++))
+			result="${result} [${file}] newday:[$(date +%F_%T)] ### rollback:[${dstfile}] ### ###"
 			continue
 		}
 
@@ -96,7 +115,8 @@ check() {
 				done
 
 			    	mv "${file}" "${dstfile}" 2>&-
-			    	result="${result} [${file}] newday logitem:[${tail_day} <> ${head_day}]: roll back [${file}] => [${dstfile}];"
+				((rollnum++))
+			    	result="${result} [${file}] newlog:[${tail_day} <> ${head_day}] ### rollback:[${dstfile}] ### ###"
 			    	continue
 			}
 		}
@@ -117,15 +137,30 @@ check() {
 				done
 	
 				mv "${file}" "${dstfile}" 2>&-
-				result="${result} [${file}] [ headday: ${head_day} <> today: ${today}]: roll back [${file}] => [${dstfile}];"
+				((rollnum++))
+				result="${result} [${file}] headday:[${head_day} <> today] ### rollback:[${dstfile}] ### ###"
 				continue
 			}
 		}
-	}
+	fi
   done
   
-  [ -z "${result//[ ]}" ] && result="Nothing to do"
-  echo "${result}"
+  [ -z "${result}" ] && {
+  	EXIT_STATUS="${STATE_OK}"
+  	LEVEL="ok"
+	TYPE="str"
+	CONTENT="Nothing to do | No files to be processed"
+  } || {
+	EXIT_STATUS="${STATE_OK}"
+	LEVEL="ok"
+	TYPE="str"
+	CONTENT="RollBack finished | ${rollnum} files rolled back | ${result}"
+  }
+
 }
 
 check
+
+# output result and return exit status here.
+echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
+exit ${EXIT_STATUS}
diff --git a/plugin/.inner/eminfo_self_check b/plugin/.inner/eminfo_self_check
--- a/plugin/.inner/eminfo_self_check
+++ b/plugin/.inner/eminfo_self_check
@@ -4,45 +4,88 @@
 # Inner Plugin:  periodic check self.
 #
 
-if [ -z "${BASE_DIR}" ]; then
-        path=$(cd $(dirname $0) && pwd)
-        BASE_DIR=${path%/*}
-        BASE_DIR=${BASE_DIR%/*}
-        source ${BASE_DIR}/bin/include 2>&-
+BASE_DIR="/usr/local/eminfo"
+if [ -f ${BASE_DIR}/bin/include -a -s ${BASE_DIR}/bin/include ]; then
+        source ${BASE_DIR}/bin/include 2>&1
+        rc=$?
+        [ "$rc" != "0" ] && {
+                echo "load include file failed with status $rc"
+                exit 1
+        }   
+else
+        echo "${BASE_DIR}/bin/include not exist or empty. exit" 
+        exit 1
 fi
 
+# Return Codes
+STATE_OK=0
+STATE_WARNING=1
+STATE_CRITICAL=2
+STATE_UNKNOWN=3
+STATE_NOOP=4
 
+# Set Default
+EXIT_STATUS=0
+LEVEL=          ### { ok | warn | crit | unknown }
+TYPE=           ### { str| file }
+CONTENT=        ### { strings | /path/to/result.file }
 
 # Read plugin config value here
 
-# if null or invalid set default.
-
 # check function here
 check() {
-  local result=
+  local result=  oknum=0 warnnum=0 total=0
 
   status=$(/usr/local/eminfo/eminfo status 2>&1); rc=$?
   if [ "${rc}" != "0" ]; then
-  	result="eminfo status check return [${rc}] [${status}];"
+  	result="eminfo status check return [${rc}] [${status}] ###"
+	((warnnum++))
   else
-	result="eminfo status check return [0] OK;"
+	result="eminfo status check return [0] OK ###"
+	((oknum++))
   fi
+  ((total++))
 
   precheck=$(${PRECHECK_SH} 2>&1); rc=$?
+  precheck=$(echo -en "${precheck}" | sed -e 's/$/###/g' | tr -d '\r\n')
   if [ "${rc}" != "0" ]; then
-  	result="${result} eminfo precheck return [${rc}] [${precheck}];"
+  	result="${result} eminfo precheck return [${rc}] ### ${precheck} ###"
+	((warnnum++))
   else
-	result="${result} eminfo precheck return [0] OK;"
+	result="${result} eminfo precheck return [0] OK ###"
+	((oknum++))
   fi
+  ((total++))
 
   checkconf=$(${CHECKCONF_SH} 2>&1); rc=$?
+  checkconf=$(echo -en "${checkconf}" | sed -e 's/$/###/g' | tr -d '\r\n')
   if [ "${rc}" != "0" ]; then
-  	result="${result} eminfo checkconf return [${rc}] [${checkconf}];"
+  	result="${result} eminfo checkconf return [${rc}] ### ${checkconf} ###"
+	((warnnum++))
   else
-	result="${result} eminfo checkconf return [0] OK;"
+	result="${result} eminfo checkconf return [0] OK ###"
+	((oknum++))
   fi
+  ((total++))
 
-  echo "${result}" | tr -d '\r\n'
+  result=$(echo -en "${result}" | tr -d '\r\n')
+  if [ "${warnnum}" != "0" ]; then
+	EXIT_STATUS="${STATE_WARNING}"
+	LEVEL="warn"
+	TYPE="str"
+	CONTENT="SelfCheck FAIL | ${warnnum}/${total} check failed | ${result}"
+  else
+	EXIT_STATUS="${STATE_OK}"
+	LEVEL="ok"
+	TYPE="str"
+	CONTENT="SelfCheck Success | ${oknum}/${total} check success | ${result}"
+  fi
+  
 }
 
 check
+
+
+# output result and return exit status here.
+echo "{"${LEVEL}"}:{"${TYPE}"}:{"${CONTENT}"}"  | tr -d '\015\012'
+exit ${EXIT_STATUS}
